services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    hostname: container_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_base_rostos:/usr/share/elasticsearch/data
    networks:
      - face_network

  fastapi_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - elasticsearch
    networks:
      - face_network

volumes:
  elastic_base_rostos:

networks:
  face_network:
    driver: bridge
