services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    hostname: container_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: "2.0"        # max 2 cores
          memory: 2g         # max 2 GB RAM
        reservations:
          cpus: "1.0"
          memory: 1g
    networks:
      - face_network

  fastapi_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1.5g
        reservations:
          cpus: "0.5"
          memory: 512m
    networks:
      - face_network

networks:
  face_network:
    driver: bridge
